# Generated by Django 5.2.14 on 2026-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('student', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('task_title', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('admin_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
