# Generated by Django 6.0.5 on 2026-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task_task_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_admin',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
